#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/gay8.tar.gz
cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf gay8.tar.gz
echo "unzip done"
find gay8.tar.gz -delete
