#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/NezukoOS/manifest
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Box In A Box"
git config --global user.email evanferrao@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
pwd

git clone https://github.com/Realme-G70-Series/device_realme_rmx2020.git device/realme/rmx2020
git clone https://github.com/Realme-G70-Series/vendor_realme_rmx2020.git vendor/realme/rmx2020

#lineage--->aosp (sorry im lazy to do it on github)
cd device/realme/rmx2020 && sed -i s/lineage/aosp/g AndroidProduct.mk && sed -i s/lineage/aosp/g lineage_rmx2020.mk && mv lineage_rmx2020.mk aosp_rmx2020.mk && cd ../../..
cd /tmp/rom

cd external/selinux && curl -L http://ix.io/2FhM > sasta.patch && git am sasta.patch && cd ../..
cd frameworks/opt/net/wifi && wget https://raw.githubusercontent.com/SamarV-121/android_vendor_extra/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch && patch -p1 < *.patch && cd -
cd frameworks/opt/net/ims && wget https://raw.githubusercontent.com/SamarV-121/android_vendor_extra/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch && patch -p1 < *.patch && cd -
cd frameworks/av && wget https://github.com/phhusson/platform_frameworks_av/commit/624cfc90b8bedb024f289772960f3cd7072fa940.patch && patch -p1 < *.patch && cd -
cd /tmp/rom
ls device/realme/rmx2020
df-h
ls
